language: python
python:
  - 2.7
cache: pip
install:
  - pip install awscli
  - pip install mkdocs
  - pip install mkdocs-material
script:
  - mkdocs build --clean
deploy:
  on:
    branch: master
    repo: 'PagerDuty/incident-response-docs'
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: site
  acl: public_read
after_deploy:
  # Delete any old files from the S3 bucket.
  - aws s3 sync site/ s3://$AWS_S3_BUCKET --acl public-read --exclude "*.py*" --delete
