# Project Information
site_name: PagerDuty Incident Response Documentation
site_description: A collection of information about the PagerDuty incident response process. Not only how to prepare new employees for on-call responsibilities, but also how to handle major incidents, both in preparation and after-work.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://response.pagerduty.com

# Repository
repo_url: https://github.com/pagerduty/incident-response-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Contents
pages:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - On-Call:
    - Being On-Call: 'oncall/being_oncall.md'
    - Who's On-Call?: 'oncall/whos_oncall.md'
    - Alerting Principles: 'oncall/alerting_principles.md'
  - Before an Incident:
    - What is an Incident?: 'before/what_is_an_incident.md'
    - Severity Levels: 'before/severity_levels.md'
    - Different Roles: 'before/different_roles.md'
    - Call Etiquette: 'before/call_etiquette.md'
    - Complex Incidents: 'before/complex_incidents.md'
  - During an Incident:
    - During an Incident: 'during/during_an_incident.md'
    - Security Incident: 'during/security_incident_response.md'
  - After an Incident:
    - After an Incident: 'after/after_an_incident.md'
    - Post-Mortem Process: 'after/post_mortem_process.md'
    - Post-Mortem Template: 'after/post_mortem_template.md'
    - Effective Post-Mortems: 'after/effective_post_mortems.md'
  - Training:
    - Overview: 'training/overview.md'
    - Incident Commander: 'training/incident_commander.md'
    - Deputy: 'training/deputy.md'
    - Scribe: 'training/scribe.md'
    - Subject Matter Expert: 'training/subject_matter_expert.md'
    - Customer Liaison: 'training/customer_liaison.md'
    - Internal Liaison: 'training/internal_liaison.md'
    - Glossary: 'training/glossary.md'
  - Training Courses:
    - Incident Response: 'training/courses/incident_response.md'
  - Additional Resources:
    - Reading: 'resources/reading.md'
    - ChatOps: 'resources/chatops.md'
    - Anti-Patterns: 'resources/anti_patterns.md'
  - About: 'about.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
